### ISSUE TITLE
Main menu doesn't give touch feedback.

### ISSUE THREAD

**Issue by s4436555** [s4436555/R-D-P-game#3]
I think that the pressed option should be highlighted.

**Comment by FunctionalGhost** [comment]
next on my list

**Comment by FunctionalGhost** [comment]
heb de theorie; ga morgen pushen

**Comment by FunctionalGhost** [comment]
Te moeilijk; ik ga eerst andere dingen doen die belngrijker zijn.

**Comment by s4436555** [comment]
Ik gebruik dit gewoon om dingen bij te houden die nog moeten gebeuren die niet compleet voor de hand liggen. Dingen zoals enhancements hebben doorgaans niet zo'n hoge prioriteit...

**Comment by OsthatoAlfakyn** [comment]
Lijkt me voltooid
